services:
  - type: web
    name: creator-portal
    runtime: docker
    dockerfilePath: ./apps/portal/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - fromGroup: creator commerce

  - type: web
    name: design-engine
    runtime: docker
    dockerfilePath: ./design-engine/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - fromGroup: creator commerce
